spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vanha_store
    username: postgres
    password: backenddev
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

cloudinary:
  cloud_name: dpuascmen
  api_key: 652888563957622
  api_secret: XwZcuNCZnnoNovKuIKbg0ux50Vo